name: Build Windows binaries

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  msys:
    runs-on: windows-2019
    strategy:
      matrix:
        mingw: ["MINGW32", "MINGW64"]
        include:
          - mingw: "MINGW32"
            package: "mingw-w64-i686"
          - mingw: "MINGW64"
            package: "mingw-w64-x86_64"
    defaults:
      run:
        shell: bash.exe --login -eo pipefail "{0}"
    env:
      MSYSTEM: ${{ matrix.mingw }}
      CHERE_INVOKING: 1
    name: MSYS2 ${{ matrix.mingw }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up shell
        run: echo "C:\msys64\usr\bin\" >> $GITHUB_PATH
        shell: pwsh
      - name: Print system version
        run: |
          uname
      - name: Install MinGW requirements
        run: |
          echo "$GITHUB_WORKSPACE"
          #pacman -S --noconfirm ${{ matrix.package }}-python3-setuptools
          # build the project
          #python3 setup.py install
      - name: Build binaries
        run: |
          make
          # add .exe extension to binaries
          mv diablo3-decrypter/diablo3-ps3save-decrypter diablo3-ps3save-decrypter.exe
          mv re-remaster-decrypter/re-remaster-decrypter re-remaster-decrypter.exe
          mv dmc-decrypter/dmc-ps3save-decrypter dmc-ps3save-decrypter.exe
          mv naughtydog-decrypter/naughtydog-ps3save-decrypter naughtydog-ps3save-decrypter.exe
          mv re-revelations2-decrypter/re-revelations2-decrypter re-revelations2-decrypter.exe
          mv ff13-decrypter/ff13-ps3save-decrypter ff13-ps3save-decrypter.exe
          mv nfs-rivals-decrypter/nfsrivals-ps3save-decrypter nfsrivals-ps3save-decrypter.exe
          mv silent-hill3-decrypter/silent-hill3-decrypter silent-hill3-decrypter.exe
          mv cod-blackops-decrypter/cod-blackops-decrypter cod-blackops-decrypter.exe
          mv nfs-undercover-decrypter/nfs-undercover-decrypter nfs-undercover-decrypter.exe
          mv gta5-decrypter/gta5-ps3save-decrypter gta5-ps3save-decrypter.exe
          mv deadspace-checksum-fixer/ds-checksum-fixer ds-checksum-fixer.exe
          mv ffxhd-checksum-fixer/ffxhd-checksum-fixer ffxhd-checksum-fixer.exe
          mv kh25-checksum-fixer/kh25remix-checksum-fixer kh25remix-checksum-fixer.exe
          mv prototype-checksum-fixer/prototype-checksum-fixer prototype-checksum-fixer.exe

      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
    
      - name: Compress output
        run: |
          tar -zcvf build.tar.gz diablo3-ps3save-decrypter.exe \
            kh25remix-checksum-fixer.exe \
            re-remaster-decrypter.exe \
            dmc-ps3save-decrypter.exe \
            naughtydog-ps3save-decrypter.exe \
            re-revelations2-decrypter.exe \
            ff13-ps3save-decrypter.exe \
            nfsrivals-ps3save-decrypter.exe \
            silent-hill3-decrypter.exe \
            cod-blackops-decrypter.exe \
            ffxhd-checksum-fixer.exe \
            nfs-undercover-decrypter.exe \
            ds-checksum-fixer.exe \
            gta5-ps3save-decrypter.exe \
            prototype-checksum-fixer.exe

      - uses: actions/upload-artifact@v2
        with:
          name: build-${{ steps.slug.outputs.sha8 }}-${{matrix.mingw}}
          path: build.tar.gz
